# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  sln: './Bunnypro.GeneticAlgorithm.sln'
  tests_core: './tests/Core.Test/Bunnypro.GeneticAlgorithm.Core.Test.csproj'
  tests_ext: './tests/Extensions.Test/Bunnypro.GeneticAlgorithm.Extensions.Test.csproj'

steps:
- script: dotnet build --configuration $(buildConfiguration) $(sln)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test $(tests_core) --logger "xunit;LogFileName=TestResults.xml"
  displayName: 'Genetic ALgorithm Core Test'
- script: dotnet test $(tests_ext) --logger "xunit;LogFileName=TestResults.xml"
  displayName: 'Genetic ALgorithm Extensions Test'
- task: PublishTestResults@2
  displayName: 'publish test results to azure pipelines'
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TestResults.xml'
  condition: always()
